BEGIN TRANSACTION

DROP TABLE BILLING
DROP TABLE DOCTOR
DROP TABLE STAFF
DROP TABLE INDOOR_PATIENT
DROP TABLE OUTDOOR_PATIENT
DROP TABLE ROOM
DROP TABLE PATIENT_ENCOUNTER
DROP TABLE ADMISSION
DROP TABLE DEPARTMENT_HOSP

COMMIT TRANSACTION